# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb4250d69c42a7135daa5e704c8879089113657d1ab10e9a6712c1fe9c71b3165bb168d6fef2b46ac3a5188f6cbcf7f6bac5764f5e88027b995246f4d59c2f2f

test:
  secret_key_base: f30e8cf6f6d374525c3526fbf4e93419800d608a6c187f3a6da12e8f8538bc869b0e4dbf846e9b0c784d3dd9a2c7e446e0b1765cebfdc657b11cf119d6a38d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
